-- This resource was generated by grzyClothTool :)
-- discord.gg/HCQutNhxWt

fx_version 'cerulean'
game 'gta5'
author 'grzyClothTool'

files {
  'mp_f_freemode_01_sheep_icecream_sundaypost_female.meta'
}

data_file 'SHOP_PED_APPAREL_META_FILE' 'mp_f_freemode_01_sheep_icecream_sundaypost_female.meta'
